[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416b110>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416b5c0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10416bd10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1045050a0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104504b90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104507770>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/118f56f2-7fc1-4a19-a497-a11b8224f7f4/screenshot