[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040d7c80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10401d9d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040d7b30>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040d6f00>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040d6900>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1040d6960>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/02a33a2d-cd65-4d27-90b2-402c34126529/screenshot