[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10465b710>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10465aff0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10465a2d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/source
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10465b410>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10465b890>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/screenshot
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:874 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1046582f0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a9f7d398-1a8e-415a-85b1-abba7722a860/screenshot